/**
 * Statewide Activity Service
 * Manages the Statewide Activity table for heatmap data
 * Auto-deletes records older than 90 days
 */

import { normalizeSection, normalizeAPI } from '../utils/normalize.js';

const AIRTABLE_API_BASE = 'https://api.airtable.com/v0';

/**
 * Create a statewide activity record
 * @param {Object} env - Worker environment
 * @param {Object} activityData - Activity data
 * @returns {Object} - Result of the operation
 */
export async function createStatewideActivity(env, activityData) {
  const apiNumber = normalizeAPI(activityData.apiNumber);
  if (!apiNumber) {
    return { success: false, error: 'No API number provided' };
  }
  
  // First, check if a record already exists for this API
  try {
    const existingUrl = `${AIRTABLE_API_BASE}/${env.AIRTABLE_BASE_ID}/${env.AIRTABLE_STATEWIDE_ACTIVITY_TABLE}?filterByFormula={API Number}='${apiNumber}'&maxRecords=1`;
    
    const existingResponse = await fetch(existingUrl, {
      headers: {
        'Authorization': `Bearer ${env.MINERAL_AIRTABLE_API_KEY}`,
        'Content-Type': 'application/json'
      }
    });
    
    if (existingResponse.ok) {
      const existingData = await existingResponse.json();
      if (existingData.records && existingData.records.length > 0) {
        // Record exists - update it if we have new data
        const existingRecord = existingData.records[0];
        const recordId = existingRecord.id;
        const existingFields = existingRecord.fields;
        
        // Only update if we have MORE data than existing record
        const hasNewBHData = (activityData.bhLatitude && !existingFields['BH Latitude']) ||
                            (activityData.bhSection && !existingFields['BH Section']);
        const hasNewCoords = (activityData.latitude && !existingFields['Latitude']);
        
        if (hasNewBHData || hasNewCoords || activityData.activityType === 'Completion') {
          console.log(`[Statewide] Updating existing record for ${apiNumber} with new data`);
          return await updateStatewideActivity(env, recordId, activityData);
        } else {
          console.log(`[Statewide] Record already exists for ${apiNumber}, skipping`);
          return { success: true, action: 'skipped', id: recordId };
        }
      }
    }
  } catch (err) {
    console.warn(`[Statewide] Error checking existing record for ${apiNumber}:`, err.message);
    // Continue with creation if check fails
  }
  
  // Build fields object
  const fields = {
    'API Number': apiNumber,
    // Note: 'Activity Type' field doesn't exist in Airtable, use Has Permit/Has Completion instead
    'Has Permit': activityData.activityType === 'Permit',
    'Has Completion': activityData.activityType === 'Completion',
    // Note: 'Created At' is auto-generated by Airtable, not needed here
  };
  
  // Basic information
  if (activityData.wellName) fields['Well Name'] = activityData.wellName;
  if (activityData.operator) fields['Operator'] = activityData.operator;
  if (activityData.county) fields['County'] = activityData.county;
  if (activityData.formation) fields['Formation'] = activityData.formation;
  
  // Location data - use Surface prefix as seen in Airtable
  if (activityData.section) fields['Surface Section'] = normalizeSection(activityData.section);
  if (activityData.township) fields['Surface Township'] = activityData.township;
  if (activityData.range) fields['Surface Range'] = activityData.range;
  if (activityData.pm) fields['Surface PM'] = activityData.pm;
  
  // Bottom hole location data for horizontal wells
  if (activityData.bhSection) fields['BH Section'] = normalizeSection(activityData.bhSection);
  if (activityData.bhTownship) fields['BH Township'] = activityData.bhTownship;
  if (activityData.bhRange) fields['BH Range'] = activityData.bhRange;
  if (activityData.bhPM) fields['BH PM'] = activityData.bhPM;
  
  // Coordinates - REQUIRED for heatmap
  if (activityData.latitude !== undefined && activityData.latitude !== null) {
    fields['Latitude'] = activityData.latitude;
  }
  if (activityData.longitude !== undefined && activityData.longitude !== null) {
    fields['Longitude'] = activityData.longitude;
  }
  if (activityData.bhLatitude !== undefined && activityData.bhLatitude !== null) {
    fields['BH Latitude'] = activityData.bhLatitude;
  }
  if (activityData.bhLongitude !== undefined && activityData.bhLongitude !== null) {
    fields['BH Longitude'] = activityData.bhLongitude;
  }
  
  // Optional fields
  if (activityData.mapLink) fields['OCC Map Link'] = activityData.mapLink;
  if (activityData.permitDate) fields['Permit Date'] = activityData.permitDate;
  if (activityData.completionDate) fields['Completion Date'] = activityData.completionDate;
  if (activityData.isHorizontal !== undefined) fields['Is Horizontal'] = activityData.isHorizontal;
  
  try {
    const createUrl = `${AIRTABLE_API_BASE}/${env.AIRTABLE_BASE_ID}/${env.AIRTABLE_STATEWIDE_ACTIVITY_TABLE}`;
    
    const createResponse = await fetch(createUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${env.MINERAL_AIRTABLE_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ fields })
    });
    
    if (!createResponse.ok) {
      const error = await createResponse.text();
      return { success: false, error: `Create failed: ${error}` };
    }
    
    return { success: true, action: 'created', apiNumber };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

/**
 * Clean up old statewide activity records
 * @param {Object} env - Worker environment
 * @param {number} daysToKeep - Number of days to keep records (default 90)
 * @returns {Object} - Cleanup results
 */
export async function cleanupOldStatewideRecords(env, daysToKeep = 90) {
  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - daysToKeep);
  
  // Find records older than cutoff
  const formula = `DATETIME_DIFF(NOW(), {Created Date}, 'days') > ${daysToKeep}`;
  const url = `${AIRTABLE_API_BASE}/${env.AIRTABLE_BASE_ID}/${env.AIRTABLE_STATEWIDE_ACTIVITY_TABLE}?filterByFormula=${encodeURIComponent(formula)}&fields[]=id`;
  
  try {
    const response = await fetch(url, {
      headers: {
        'Authorization': `Bearer ${env.MINERAL_AIRTABLE_API_KEY}`,
        'Content-Type': 'application/json'
      }
    });
    
    if (!response.ok) {
      return { success: false, error: 'Failed to fetch old records' };
    }
    
    const data = await response.json();
    const recordsToDelete = data.records || [];
    
    if (recordsToDelete.length === 0) {
      return { success: true, deletedCount: 0 };
    }
    
    // Delete in batches of 10 (Airtable limit)
    let deletedCount = 0;
    for (let i = 0; i < recordsToDelete.length; i += 10) {
      const batch = recordsToDelete.slice(i, i + 10);
      const deleteUrl = `${AIRTABLE_API_BASE}/${env.AIRTABLE_BASE_ID}/${env.AIRTABLE_STATEWIDE_ACTIVITY_TABLE}`;
      
      const deleteParams = new URLSearchParams();
      batch.forEach(record => {
        deleteParams.append('records[]', record.id);
      });
      
      const deleteResponse = await fetch(`${deleteUrl}?${deleteParams}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${env.MINERAL_AIRTABLE_API_KEY}`
        }
      });
      
      if (deleteResponse.ok) {
        deletedCount += batch.length;
      }
    }
    
    return { success: true, deletedCount };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

/**
 * Create statewide activity data from a permit
 */
export function createStatewideActivityFromPermit(permit, wellCoords = null, mapLink = null) {
  const activityData = {
    apiNumber: normalizeAPI(permit.API_Number),
    activityType: 'Permit',
    wellName: `${permit.Well_Name || ''} ${permit.Well_Number || ''}`.trim(),
    operator: permit.Entity_Name,
    county: permit.County,
    section: permit.Section,
    township: permit.Township,
    range: permit.Range,
    pm: permit.PM || 'IM',
    permitDate: (() => {
      const rawDate = permit.Approval_Date;
      console.log(`[Debug] Raw permit date for ${permit.API_Number}: "${rawDate}" (type: ${typeof rawDate})`);
      
      if (rawDate && typeof rawDate === 'string' && rawDate.trim()) {
        const trimmed = rawDate.trim();
        // Try to parse and reformat the date
        const parsed = new Date(trimmed);
        if (!isNaN(parsed)) {
          const formatted = parsed.toISOString().split('T')[0];
          console.log(`[Debug] Formatted permit date: "${formatted}"`);
          return formatted;
        }
        console.log(`[Debug] Invalid date string: "${trimmed}"`);
      }
      
      const fallback = new Date().toISOString().split('T')[0];
      console.log(`[Debug] Using fallback permit date: "${fallback}"`);
      return fallback;
    })(),
    isHorizontal: (() => {
      // Check drill type
      const isHorizontalByType = permit.Drill_Type === 'HH' || permit.Drill_Type === 'DH';
      
      // Check well name patterns (common horizontal well naming conventions)
      const wellName = permit.Well_Name || '';
      const isHorizontalByName = /\d+H$|MXH$|HXH$|BXH$|SXH$|UXH$|LXH$|H\d+$|-H$|_H$/i.test(wellName);
      
      return isHorizontalByType || isHorizontalByName;
    })()
  };
  
  // First priority: Extract coordinates directly from OCC permit data
  if (permit.Surf_Lat_Y && permit.Surf_Long_X) {
    // Parse coordinates from OCC data - they're usually strings
    const latitude = parseFloat(permit.Surf_Lat_Y);
    const longitude = parseFloat(permit.Surf_Long_X);
    
    // Validate the coordinates are reasonable for Oklahoma
    if (!isNaN(latitude) && !isNaN(longitude) && 
        latitude > 33 && latitude < 37 && 
        longitude > -103 && longitude < -94) {
      activityData.latitude = latitude;
      activityData.longitude = longitude;
      console.log(`[Statewide] Using OCC permit coordinates for ${permit.API_Number}: ${latitude}, ${longitude}`);
    } else {
      console.log(`[Statewide] Invalid OCC permit coordinates for ${permit.API_Number}: ${permit.Surf_Lat_Y}, ${permit.Surf_Long_X}`);
    }
  }
  
  // Second priority: Use GIS API or fallback coordinates if no OCC coordinates
  if (!activityData.latitude && !activityData.longitude && wellCoords && wellCoords.sh_lat && wellCoords.sh_lon) {
    activityData.latitude = wellCoords.sh_lat;
    activityData.longitude = wellCoords.sh_lon;
  }
  
  // Extract BH coordinates if available for horizontal wells
  if (activityData.isHorizontal) {
    if (permit.BH_Lat_Y && permit.BH_Long_X) {
      const bhLatitude = parseFloat(permit.BH_Lat_Y);
      const bhLongitude = parseFloat(permit.BH_Long_X);
      
      // Validate BH coordinates are reasonable for Oklahoma
      if (!isNaN(bhLatitude) && !isNaN(bhLongitude) && 
          bhLatitude > 33 && bhLatitude < 37 && 
          bhLongitude > -103 && bhLongitude < -94) {
        activityData.bhLatitude = bhLatitude;
        activityData.bhLongitude = bhLongitude;
        console.log(`[Statewide] Using OCC permit BH coordinates for ${permit.API_Number}: ${bhLatitude}, ${bhLongitude}`);
      }
    }
  }
  
  // Add map link if available
  if (mapLink) {
    activityData.mapLink = mapLink;
  }
  
  return activityData;
}

/**
 * Create statewide activity data from a completion
 */
export function createStatewideActivityFromCompletion(completion, wellCoords = null, mapLink = null) {
  const activityData = {
    apiNumber: normalizeAPI(completion.API_Number),
    activityType: 'Completion',
    wellName: `${completion.Well_Name || ''} ${completion.Well_Number || ''}`.trim(),
    operator: completion.Operator_Name || completion.Operator,
    county: completion.County,
    section: completion.Section,
    township: completion.Township,
    range: completion.Range,
    pm: completion.PM || 'IM',
    formation: completion.Formation_Name,
    completionDate: (completion.Well_Completion && completion.Well_Completion.trim()) || new Date().toISOString(),
    isHorizontal: completion.Drill_Type === 'HORIZONTAL HOLE'
  };
  
  // First priority: Extract coordinates directly from OCC completion data
  if (completion.Surf_Lat_Y && completion.Surf_Long_X) {
    // Parse coordinates from OCC data - they're usually strings
    const latitude = parseFloat(completion.Surf_Lat_Y);
    const longitude = parseFloat(completion.Surf_Long_X);
    
    // Validate the coordinates are reasonable for Oklahoma
    if (!isNaN(latitude) && !isNaN(longitude) && 
        latitude > 33 && latitude < 37 && 
        longitude > -103 && longitude < -94) {
      activityData.latitude = latitude;
      activityData.longitude = longitude;
      console.log(`[Statewide] Using OCC completion coordinates for ${completion.API_Number}: ${latitude}, ${longitude}`);
    } else {
      console.log(`[Statewide] Invalid OCC completion coordinates for ${completion.API_Number}: ${completion.Surf_Lat_Y}, ${completion.Surf_Long_X}`);
    }
  }
  
  // Second priority: Use GIS API or fallback coordinates if no OCC coordinates
  if (!activityData.latitude && !activityData.longitude && wellCoords && wellCoords.sh_lat && wellCoords.sh_lon) {
    activityData.latitude = wellCoords.sh_lat;
    activityData.longitude = wellCoords.sh_lon;
  }
  
  // Extract BH coordinates and location if available for horizontal wells
  if (completion.Drill_Type === 'HORIZONTAL HOLE' || completion.Drill_Type === 'HH') {
    // Add bottom hole section/township/range data
    if (completion.BH_Section) activityData.bhSection = completion.BH_Section;
    if (completion.BH_Township) activityData.bhTownship = completion.BH_Township;
    if (completion.BH_Range) activityData.bhRange = completion.BH_Range;
    if (completion.BH_PM) activityData.bhPM = completion.BH_PM;
    
    // Extract bottom hole coordinates - note the field names are different from permits
    if (completion.Bottom_Hole_Lat_Y && completion.Bottom_Hole_Long_X) {
      const bhLatitude = parseFloat(completion.Bottom_Hole_Lat_Y);
      const bhLongitude = parseFloat(completion.Bottom_Hole_Long_X);
      
      // Validate BH coordinates are reasonable for Oklahoma
      if (!isNaN(bhLatitude) && !isNaN(bhLongitude) && 
          bhLatitude > 33 && bhLatitude < 37 && 
          bhLongitude > -103 && bhLongitude < -94) {
        activityData.bhLatitude = bhLatitude;
        activityData.bhLongitude = bhLongitude;
        console.log(`[Statewide] Using OCC completion BH coordinates for ${completion.API_Number}: ${bhLatitude}, ${bhLongitude}`);
      }
    }
    
    // Add direction and length if available
    if (completion.Direction) activityData.direction = parseFloat(completion.Direction);
    if (completion.Length) activityData.length = parseFloat(completion.Length);
  }
  
  // Add map link if available
  if (mapLink) {
    activityData.mapLink = mapLink;
  }
  
  return activityData;
}

/**
 * Update an existing statewide activity record with new data
 * @param {Object} env - Worker environment
 * @param {string} recordId - Airtable record ID
 * @param {Object} activityData - New activity data
 * @returns {Object} - Result of the update
 */
async function updateStatewideActivity(env, recordId, activityData) {
  // Build update fields - only include non-empty values
  const updateFields = {};
  
  // Update basic fields if provided
  if (activityData.wellName) updateFields["Well Name"] = activityData.wellName;
  if (activityData.operator) updateFields["Operator"] = activityData.operator;
  if (activityData.formation) updateFields["Formation"] = activityData.formation;
  
  // Update coordinates if provided
  if (activityData.latitude !== undefined) updateFields["Latitude"] = activityData.latitude;
  if (activityData.longitude !== undefined) updateFields["Longitude"] = activityData.longitude;
  if (activityData.bhLatitude !== undefined) updateFields["BH Latitude"] = activityData.bhLatitude;
  if (activityData.bhLongitude !== undefined) updateFields["BH Longitude"] = activityData.bhLongitude;
  
  // Update BH location if provided
  if (activityData.bhSection) updateFields["BH Section"] = normalizeSection(activityData.bhSection);
  if (activityData.bhTownship) updateFields["BH Township"] = activityData.bhTownship;
  if (activityData.bhRange) updateFields["BH Range"] = activityData.bhRange;
  if (activityData.bhPM) updateFields["BH PM"] = activityData.bhPM;
  
  // Update activity flags
  if (activityData.activityType === "Completion") {
    updateFields["Has Completion"] = true;
    if (activityData.completionDate) updateFields["Completion Date"] = activityData.completionDate;
  }
  
  // Update other fields
  if (activityData.isHorizontal !== undefined) updateFields["Is Horizontal"] = activityData.isHorizontal;
  if (activityData.mapLink) updateFields["OCC Map Link"] = activityData.mapLink;
  
  try {
    const updateUrl = `${AIRTABLE_API_BASE}/${env.AIRTABLE_BASE_ID}/${env.AIRTABLE_STATEWIDE_ACTIVITY_TABLE}/${recordId}`;
    
    const updateResponse = await fetch(updateUrl, {
      method: "PATCH",
      headers: {
        "Authorization": `Bearer ${env.MINERAL_AIRTABLE_API_KEY}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ fields: updateFields })
    });
    
    if (!updateResponse.ok) {
      const errorText = await updateResponse.text();
      console.error(`[Statewide] Update failed for ${recordId}:`, errorText);
      return { success: false, error: errorText };
    }
    
    const result = await updateResponse.json();
    return { success: true, action: "updated", id: result.id };
  } catch (err) {
    console.error(`[Statewide] Update error for ${recordId}:`, err);
    return { success: false, error: err.message };
  }
}
