/**
 * Statewide Activity Service
 * Manages the Statewide Activity table for heatmap data
 * Auto-deletes records older than 90 days
 */

import { normalizeSection, normalizeAPI } from '../utils/normalize.js';

const AIRTABLE_API_BASE = 'https://api.airtable.com/v0';

/**
 * Create a statewide activity record
 * @param {Object} env - Worker environment
 * @param {Object} activityData - Activity data
 * @returns {Object} - Result of the operation
 */
export async function createStatewideActivity(env, activityData) {
  const apiNumber = normalizeAPI(activityData.apiNumber);
  if (!apiNumber) {
    return { success: false, error: 'No API number provided' };
  }
  
  // Build fields object
  const fields = {
    'API Number': apiNumber,
    // Note: 'Activity Type' field doesn't exist in Airtable, use Has Permit/Has Completion instead
    'Has Permit': activityData.activityType === 'Permit',
    'Has Completion': activityData.activityType === 'Completion',
    // Note: 'Created At' is auto-generated by Airtable, not needed here
  };
  
  // Basic information
  if (activityData.wellName) fields['Well Name'] = activityData.wellName;
  if (activityData.operator) fields['Operator'] = activityData.operator;
  if (activityData.county) fields['County'] = activityData.county;
  if (activityData.formation) fields['Formation'] = activityData.formation;
  
  // Location data - use Surface prefix as seen in Airtable
  if (activityData.section) fields['Surface Section'] = normalizeSection(activityData.section);
  if (activityData.township) fields['Surface Township'] = activityData.township;
  if (activityData.range) fields['Surface Range'] = activityData.range;
  // Note: PM field might not exist in the table
  
  // Coordinates - REQUIRED for heatmap
  if (activityData.latitude !== undefined && activityData.latitude !== null) {
    fields['Latitude'] = activityData.latitude;
  }
  if (activityData.longitude !== undefined && activityData.longitude !== null) {
    fields['Longitude'] = activityData.longitude;
  }
  
  // Optional fields
  if (activityData.mapLink) fields['OCC Map Link'] = activityData.mapLink;
  if (activityData.permitDate) fields['Permit Date'] = activityData.permitDate;
  if (activityData.completionDate) fields['Completion Date'] = activityData.completionDate;
  if (activityData.isHorizontal !== undefined) fields['Is Horizontal'] = activityData.isHorizontal;
  
  try {
    const createUrl = `${AIRTABLE_API_BASE}/${env.AIRTABLE_BASE_ID}/${env.AIRTABLE_STATEWIDE_ACTIVITY_TABLE}`;
    
    const createResponse = await fetch(createUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${env.MINERAL_AIRTABLE_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ fields })
    });
    
    if (!createResponse.ok) {
      const error = await createResponse.text();
      return { success: false, error: `Create failed: ${error}` };
    }
    
    return { success: true, action: 'created', apiNumber };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

/**
 * Clean up old statewide activity records
 * @param {Object} env - Worker environment
 * @param {number} daysToKeep - Number of days to keep records (default 90)
 * @returns {Object} - Cleanup results
 */
export async function cleanupOldStatewideRecords(env, daysToKeep = 90) {
  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - daysToKeep);
  
  // Find records older than cutoff
  const formula = `DATETIME_DIFF(NOW(), {Created At}, 'days') > ${daysToKeep}`;
  const url = `${AIRTABLE_API_BASE}/${env.AIRTABLE_BASE_ID}/${env.AIRTABLE_STATEWIDE_ACTIVITY_TABLE}?filterByFormula=${encodeURIComponent(formula)}&fields[]=id`;
  
  try {
    const response = await fetch(url, {
      headers: {
        'Authorization': `Bearer ${env.MINERAL_AIRTABLE_API_KEY}`,
        'Content-Type': 'application/json'
      }
    });
    
    if (!response.ok) {
      return { success: false, error: 'Failed to fetch old records' };
    }
    
    const data = await response.json();
    const recordsToDelete = data.records || [];
    
    if (recordsToDelete.length === 0) {
      return { success: true, deletedCount: 0 };
    }
    
    // Delete in batches of 10 (Airtable limit)
    let deletedCount = 0;
    for (let i = 0; i < recordsToDelete.length; i += 10) {
      const batch = recordsToDelete.slice(i, i + 10);
      const deleteUrl = `${AIRTABLE_API_BASE}/${env.AIRTABLE_BASE_ID}/${env.AIRTABLE_STATEWIDE_ACTIVITY_TABLE}`;
      
      const deleteParams = new URLSearchParams();
      batch.forEach(record => {
        deleteParams.append('records[]', record.id);
      });
      
      const deleteResponse = await fetch(`${deleteUrl}?${deleteParams}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${env.MINERAL_AIRTABLE_API_KEY}`
        }
      });
      
      if (deleteResponse.ok) {
        deletedCount += batch.length;
      }
    }
    
    return { success: true, deletedCount };
  } catch (err) {
    return { success: false, error: err.message };
  }
}

/**
 * Create statewide activity data from a permit
 */
export function createStatewideActivityFromPermit(permit, wellCoords = null, mapLink = null) {
  const activityData = {
    apiNumber: normalizeAPI(permit.API_Number),
    activityType: 'Permit',
    wellName: `${permit.Well_Name || ''} ${permit.Well_Number || ''}`.trim(),
    operator: permit.Entity_Name,
    county: permit.County,
    section: permit.Section,
    township: permit.Township,
    range: permit.Range,
    pm: permit.PM || 'IM',
    permitDate: permit.Approval_Date || new Date().toISOString(),
    isHorizontal: permit.Drill_Type === 'HH' || permit.Drill_Type === 'DH'
  };
  
  // Add coordinates if available
  if (wellCoords && wellCoords.sh_lat && wellCoords.sh_lon) {
    activityData.latitude = wellCoords.sh_lat;
    activityData.longitude = wellCoords.sh_lon;
  }
  
  // Add map link if available
  if (mapLink) {
    activityData.mapLink = mapLink;
  }
  
  return activityData;
}

/**
 * Create statewide activity data from a completion
 */
export function createStatewideActivityFromCompletion(completion, wellCoords = null, mapLink = null) {
  const activityData = {
    apiNumber: normalizeAPI(completion.API_Number),
    activityType: 'Completion',
    wellName: `${completion.Well_Name || ''} ${completion.Well_Number || ''}`.trim(),
    operator: completion.Operator_Name || completion.Operator,
    county: completion.County,
    section: completion.Section,
    township: completion.Township,
    range: completion.Range,
    pm: completion.PM || 'IM',
    formation: completion.Formation_Name,
    completionDate: completion.Well_Completion || new Date().toISOString(),
    isHorizontal: completion.Drill_Type === 'HORIZONTAL HOLE'
  };
  
  // Add coordinates if available
  if (wellCoords && wellCoords.sh_lat && wellCoords.sh_lon) {
    activityData.latitude = wellCoords.sh_lat;
    activityData.longitude = wellCoords.sh_lon;
  }
  
  // Add map link if available
  if (mapLink) {
    activityData.mapLink = mapLink;
  }
  
  return activityData;
}