#!/bin/bash
# Execute OTC leases import
# Generated by import-otc-leases.py
echo "Importing OTC lease data (237077 records in 475 batches)..."
echo ""

FAILED=0
SUCCESS=0

for file in otc-leases-batches/batch_*.sql; do
    echo -n "Processing $file... "
    result=$(wrangler d1 execute oklahoma-wells --remote --file="$file" 2>&1)
    if echo "$result" | grep -q '"success": true'; then
        echo "OK"
        ((SUCCESS++))
    else
        echo "FAILED"
        ((FAILED++))
    fi
    sleep 0.2  # Rate limit
done

echo ""
echo "Import complete: $SUCCESS succeeded, $FAILED failed"
